### ISSUE TITLE
Error: Call to undefined function dpm() in card_recipe_install()

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/card_recipe#2]
Seems to prevent it from creating the demo content, though the content type is created.

Error: Call to undefined function dpm() in card_recipe_install() (line 150 of /app/docroot/modules/card_recipe/card_recipe.install).

**Comment by keiserjb** [comment]
Yep, comment that line out and everything works correctly.

**Comment by stpaultim** [comment]
Fixed and new release issued.
